name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12
    - name: Install Packages
      run: npm install
    - name: Build page
      run: npm run build
    - name: Install Surge
      run: npm install -g surge
    - name: Run surge
      run: surge ./build bootcamp_react_mbilal.surge.sh --token ${{ secrets.SURGE_TOKEN }}

          
